[32mINFO    [0m root:test_add_a_new_post.py:20 ----------------Test Started----------------
[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:135 Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:135 Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)